config/routes.rb
Rails.application.routes.draw do
  resources :statements, only: [:new, :show, :create]
  resources :deposits, only: [:new, :create]
  resources :withdrawals, only: [:new, :create]
  resources :transfers, only: [:new, :create]
  devise_for :accounts, controllers: { registrations: 'registrations' }
  root to: 'site#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable
  validates_presence_of :name

  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  def active_for_authentication?
    super && !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :deleted_account
  end
end

app/models/deposit.rb
class Deposit < Transaction
  validates_presence_of :target_account
end

app/models/statement.rb
class Statement
  include ActiveModel::Model

  attr_accessor :start_date, :end_date

  validates_presence_of :start_date
  validates_presence_of :end_date
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :source_account, class_name: 'Account', foreign_key: 'source_account_id'
  belongs_to :target_account, class_name: 'Account', foreign_key: 'target_account_id'
  attr_accessor :target_account_email, :source_account_email
  validates :value, numericality: { greater_than: 0 }
end

app/models/transfer.rb
class Transfer < Transaction
  validates_presence_of :source_account
  validates_presence_of :target_account
end

app/models/withdrawal.rb
class Withdrawal < Transaction
  validates_presence_of :source_account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/deposits_controller.rb
class DepositsController < TransactionsController
  private

  def transaction_class
    Deposit
  end

  def transaction_params
    params.require(:deposit).permit(:target_account_email, :value)
  end

  def call_service
    MakeDeposit.new(
      account_signed_in? ? current_account.email : transaction_params[:target_account_email],
      transaction_params[:value]
    ).run
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource) { redirect_to after_sign_out_path_for(resource_name) }
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  private

  def sign_up_params
    params.require(:account).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:account).permit(:name, :email)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    if !account_signed_in?
      redirect_to new_account_session_path unless account_signed_in?
    else
      load_last_transactions
    end
  end

  private
  def load_last_transactions
    @transactions = RequestBankStatement.new(
      current_account,
      Date.today.beginning_of_day,
      Date.today.end_of_day
    ).run[0..4]
  end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :authenticate_account!
  def new
    @statement = Statement.new
  end

  def show
  end

  def create
    set_statement
    if @statement.valid?
      retrieve_transactions(@statement)
      render action: :show
    else
      render action: :new
    end
  end

  private

  def set_statement
    @statement = Statement.new(
      start_date: statement_params[:start_date],
      end_date: statement_params[:end_date]
    )
  end

  def retrieve_transactions(statement)
    @transactions = RequestBankStatement.new(
      current_account,
      Date.parse(statement.start_date),
      Date.parse(statement.end_date)
    ).run
  end

  def statement_params
    params.require(:statement).permit(:start_date, :end_date)
  end
end

app/controllers/transactions_controller.rb
# Controller responsável por definir as ações de todas as transações.
# É necessário definir os métodos transaction_class, transaction_params e call_service.

class TransactionsController < ApplicationController

  def new
    @transaction ||= transaction_class.new
  end

  def create
    @transaction = call_service
    if @transaction.persisted?
      redirect_to root_url, notice: t("success_#{transaction_class.to_s.downcase}")
    else
      render action: :new
    end
  end

end

app/controllers/transfers_controller.rb
class TransfersController < TransactionsController
  before_action :authenticate_account!
  private

  def transaction_class
    Transfer
  end

  def transaction_params
    params.require(:transfer).permit(:target_account_email, :value)
  end

  def call_service
    MakeTransfer.new(
      current_account.email,
      transaction_params[:target_account_email],
      transaction_params[:value]
    ).run
  end
end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < TransactionsController
  before_action :authenticate_account!
  private

  def transaction_class
    Withdrawal
  end

  def transaction_params
    params.require(:withdrawal).permit(:value)
  end

  def call_service
    MakeWithdrawal.new(
      current_account.email,
      transaction_params[:value]
    ).run
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_error_messages(element)
    return '' if element.errors.empty?

    messages = element.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: element.errors.count,
                      resource: element.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-dismissible alert-danger">
      <strong><h4>#{sentence}</h2></strong>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    render_error_messages(resource)
  end
end

app/helpers/site_helper.rb
module SiteHelper
  def message_key(key)
    return 'success' if key == 'notice'
    return 'danger' if key == 'alert'
    key
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def show_target_id?(element)
    element.class != Withdrawal &&
      !(element.class == Deposit && account_signed_in?)
  end

  def show_source_id?(element)
    element.class != Deposit
  end

  def value_autofocus?(element)
    element.class == Withdrawal || (element.class == Deposit && account_signed_in?)
  end

  def transaction_title(element)
    return t(:make_deposit) if element.class == Deposit
    return t(:make_withdrawal) if element.class == Withdrawal
    t(:make_transfer)
  end
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        = t('.title')
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - if account_signed_in?
          %li
            = link_to(t('.log_out'), destroy_account_session_path, :method => :delete)
        - else
          %li
            = link_to(t('.log_in'), new_account_session_path)

app/views/layouts/_messages.html.haml
.container
  - flash.each do |key, value|
    %div{:class => "alert alert-#{message_key(key)} alert-dismissible"}
      %a.close{"data-dismiss" => "alert", type: 'button'} ×
      = value

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title
      Sistema Banco
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    = yield

  %script
    $.material.init();
    initializeDatepicker();

app/views/site/_balance_panel.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title
      %i{class:"fa fa-money"}
      = t '.title'
  .panel-body.text-center
    = number_to_currency(current_account.balance.to_f)

app/views/site/_operations_panel.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title
      = t '.title'
  .panel-body
    = link_to t('.deposit'), new_deposit_path, class: 'btn btn-default btn-raised'
    %br
    = link_to t('.withdrawal'), new_withdrawal_path, class: 'btn btn-default btn-raised'
    %br
    = link_to t('.transfer'), new_transfer_path, class: 'btn btn-default btn-raised'

app/views/site/_transactions_panel.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title
      = t '.title'
  .panel-body
    = render 'statements/transactions', locals: { transactions: @transactions }
    .text-right
      = link_to t('.generate_statement'), new_statement_path, class: 'btn btn-default btn-raised'

app/views/site/_user_panel.html.haml
.panel.panel-inverse
  .panel-heading
    %i{class:"fa fa-user"}
    = t '.title'
  .panel-body
    .col-md-9
      = Account.human_attribute_name(:email) + ': '
      = current_account.email
      %br
      = Account.human_attribute_name(:name) + ': '
      = current_account.name
      %br
    .col-md-3
      = link_to(t('.edit_account'), edit_account_registration_path, class: 'btn btn-default btn-raised')
      %br
      = link_to(t('.terminate_account'), account_registration_path, method: :delete, class: 'btn btn-default btn-raised', data: {confirm: t(:are_you_sure)})

app/views/site/index.html.haml
%br
.container
  .col-md-3
    = render 'balance_panel'
    = render 'operations_panel'
  .col-md-9
    = render 'user_panel'
    = render 'transactions_panel'

app/views/statements/_transactions.html.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th
        = Transaction.human_attribute_name(:created_at)
      %th
        = Transaction.human_attribute_name(:type)
      %th
        = Transaction.human_attribute_name(:source_account)
      %th
        = Transaction.human_attribute_name(:target_account)
      %th
        = Transaction.human_attribute_name(:value)
      %th
        = Transaction.human_attribute_name(:taxes)
  %tbody
    - @transactions.each do |transaction|
      %tr
        %th
          = l(transaction.created_at, format: :short)
        %th
          = transaction.class.model_name.human
        %th
          = transaction.source_account.nil? ? '' : transaction.source_account.email
        %th
          = transaction.target_account.nil? ? '' : transaction.target_account.email
        %th
          = transaction.value
        %th
          = transaction.taxes

app/views/statements/new.html.haml
.container
  %h2.text-center
    = t '.title'
  %br
  .col-md-6.col-md-offset-3.well.bs-component
    = form_for(@statement, html: {class: 'form-horizontal'} ) do |f|
      = render_error_messages(@statement)
      .fieldset
        .col-md-8.col-md-offset-2
          .form-group
            = f.label :start_date, class: 'control-label'
            = f.text_field :start_date, class: 'form-control datepicker'
          .form-group
            = f.label :end_date, class: 'control-label'
            = f.text_field :end_date, class: 'form-control datepicker'
          .form-group.text-center
            = f.submit t('.submit'), class: 'btn btn-primary btn-raised'

app/views/statements/show.html.haml
%br
.container
  .panel.panel-primary
    .panel-heading
      %h3.panel-title
        Extrato
    .panel-body
      = render 'statements/transactions', locals: { transactions: @transactions }

app/views/transactions/new.html.haml
.container
  %h2.text-center
    = transaction_title(@transaction)
  %br
  .col-md-6.col-md-offset-3.well.bs-component
    = form_for(@transaction, html: {class: 'form-horizontal'} ) do |f|
      = render_error_messages(@transaction)
      .fieldset
        .col-md-8.col-md-offset-2
          - if show_source_id?(@transaction) && !account_signed_in?
            .form-group
              = f.label :source_account_email, class: 'control-label'
              = f.text_field :source_account_email, autofocus: true, class: 'form-control'
          - if show_target_id?(@transaction)
            .form-group
              = f.label :target_account_email, class: 'control-label'
              = f.text_field :target_account_email, autofocus: true, class: 'form-control'
          .form-group
            = f.label :value, class: 'control-label'
            = f.text_field :value, autofocus: value_autofocus?(@transaction), class: 'form-control'
          .form-group.text-center
            = f.submit transaction_title(@transaction), class: 'btn btn-primary btn-raised'